name: Build and Deploy .NET App to Azure

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Step 5: Run tests (if any)
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Step 6: Publish the app
    - name: Publish
      run: dotnet publish -c Release -o ./publish_output

    # Step 7: Deploy to Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "ashu-learn-ci-cd" # Replace with your Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish_output
